# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0002_auto_20161012_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_date',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
