# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0004_challenge_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_status',
            field=models.CharField(choices=[(b'In progress', b'In progress'), (b'Complete', b'Complete')], default=b'In progress', max_length=11),
        ),
    ]
